-- 코드를 입력하세요
# START_DATE 와 END_DATE가 2022-11-01 ~ 2022-11-30 사이가 아닌 것.

WITH EXCEPT_CAR AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-11-30'
AND END_DATE >= '2022-11-01')

# 30일간의 대여금액이 50만원 이상 200만원 미만인 자동차

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(30 
		* (C.DAILY_FEE * (1-(IFNULL(P.DISCOUNT_RATE,0)/100))),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C LEFT JOIN EXCEPT_CAR E
ON C.CAR_ID = E.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = "30일 이상"
AND C.CAR_ID NOT IN (SELECT CAR_ID FROM EXCEPT_CAR)
AND (ROUND(30 
		* (C.DAILY_FEE * ROUND((1-(IFNULL(P.DISCOUNT_RATE,0)/100)),2)),0) BETWEEN 500000 AND 1999999)
AND (C.CAR_TYPE = "세단" OR C.CAR_TYPE = "SUV")
ORDER BY 3 DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;